on: push

name: Continuous Benchmarks

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes",  "dplyr", "plyr", "tidyr", "bib2df"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("r-lib/bench")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Fetch existing benchmarks
        run: Rscript -e 'tryCatch(bench::cb_fetch(), error = function(e) warning(e))'

      - name: Run benchmarks
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'bench::cb_run()'

      - name: Show benchmarks
        run: git notes --ref benchmarks show

      - name: Push benchmarks
        run: Rscript -e "bench::cb_push()"
