# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      
      # https://github.com/mdlincoln/clipr/blob/main/.github/workflows/R-CMD-check.yaml
      - name: Install and run XVFB
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y xvfb
          sudo /usr/bin/Xvfb :99.0 -screen 0 1280x1024x24 &
          sleep 3
      
      # https://github.com/mdlincoln/clipr/blob/main/.github/workflows/R-CMD-check.yaml
      - name: Install xclip
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y xclip
          # Initialize xclip
          uptime | xclip -i -sel p -f | xclip -i -sel c
          xclip -o -sel clipboard
        env:
          DISPLAY: ':99.0'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - uses: codecov/codecov-action@v4
        with:
          # Fail if error if not on PR, or if on PR and token is given
          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
